# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'PhotoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic   
  use_frameworks!

  # Pods for PhotoApp
  pod 'CarriersSharedAPI', path: '../../CarriersSharedAPI.podspec', testspecs: ['Tests']
end
