# Uncomment the next line to define a global platform for your project
platform :tvos, '10.0'

target 'TVExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVExample
  pod 'CarriersSharedAPI', path: '../../CarriersSharedAPI.podspec'

end
