author: XCI JV, LLC.
github_url: https://github.com/Raizlabs/XCI-ProviderSDK-iOS
theme: apple
xcodebuild_arguments: [-workspace, './Example/BankApp/BankApp.xcworkspace', -scheme, 'CarriersSharedAPI']
