author: XCI JV, LLC.
author_url: https://mobileauthtaskforce.com/
github_url: https://github.com/Raizlabs/XCI-ProviderSDK-iOS
theme: apple
xcodebuild_arguments: [-workspace, './Example/BankApp/BankApp.xcworkspace', -scheme, 'ZenKeySDK']
