# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialApp
  pod 'AppAuth', :git => 'https://github.com/openid/AppAuth-iOS', :tag => '0.95.0'
  pod 'CarriersSharedAPI', :path => '../../'
end
