# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankApp' do
  use_frameworks!

  # Pods for BankApp
  pod 'AppAuth', :git => 'https://github.com/openid/AppAuth-iOS', :tag => '0.95.0'
  pod 'CarriersSharedAPI', :path => '../../'

end
