# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'BankApp' do
  use_frameworks!
  # Pods for BankApp
  pod 'CarriersSharedAPI', path: '../../CarriersSharedAPI.podspec', testspecs: ['Tests']
end
